extends Node

enum SUIT {HEART, DIAMOND, CLUB, SPADE}
enum RANK {TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, JACK, QUEEN, KING, ACE}
enum RANK_J {TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, JACK, QUEEN, KING, ACE, JOKER}

enum CARD_STATE {DEFAULT, SELECTED, PLAYED} #TODO Hover
